version: '3'

services:
  hotelskyblue:
    build:
      context: ./lakeSide-hotel-demo-server-master # Ruta al proyecto donde está el Dockerfile
      dockerfile: Dockerfile
    container_name: hotelskyblue
    mem_limit: 1024m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod # Cambia según tu configuración
    restart: unless-stopped
