version: '3'

services:
  hotelskyblue:
    build:
      context: ./lakeSide-hotel-demo-server-master # Ruta al proyecto donde está el Dockerfile
      dockerfile: Dockerfile
    container_name: hotelskyblue
    mem_limit: 1024m
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod # Cambia según tu configuración
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hotelskyblue_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: hotelskyblue_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
